### PR TITLE
Use pandas in the post treatment 

### PR DESCRIPTION
**Pull request by FlorianTesson**

### CODE REVIEW

**Comment by FlorianTesson** [comment]
Still need to change the tests files (and to check if everything is the same)

**Comment by FlorianTesson** [comment]
Add pandas requirements

**Review by jeanrjc — APPROVED** [review]

**Comment by jeanrjc** [comment]
This could be merged @FlorianTesson ?

**Comment by FlorianTesson** [comment]
Close in favor to PR #64

**Pull request closed without merging**
